### ISSUE TITLE
feat: allow skipping errors on unreachable key

### ISSUE THREAD

**Issue by aslafy-z** [helmfile/vals#52]
`vals` could get a new cli argument that would skip resolving errors when they happen. 

## Actual behavior

```shell
$ cat <<EOF | vals eval -f - > /tmp/values.yaml
foo: bar
secret: "ref+vault://mountpoint/path/to/non-existing/key"
EOF
vault: get string failed: path="mountpoint/path/to/non-existing", key="key"
expand vault://mountpoint/path/to/non-existing/key: vault: get string: key "path/to/non-existing/key" does not exist in "mountpoint"
$ cat /tmp/values.yaml
$
```

## Expected behavior

```shell
$ cat <<EOF | vals eval --skip-errors -f - > /tmp/values.yaml
foo: bar
secret: "ref+vault://mountpoint/path/to/non-existing/key"
EOF
vault: get string failed: path="mountpoint/path/to/non-existing", key="key"
expand vault://mountpoint/path/to/non-existing/key: vault: get string: key "path/to/non-existing/key" does not exist in "mountpoint"
$ cat /tmp/values.yaml
foo: bar
$
```

**Comment by mumoshu** [comment]
@aslafy-z Hey! Thanks for the request.

I've considered this but am not sure why you need this. For example, if you're running `vals` in a CI pipeline, you'd never persist the use of `--skip-errors`, as it effectively prevents you from catching configuration errors, when you do want all the refs to be valid and present.

What's our use-case, and how are you willing to use it?

**Comment by Amos-85** [comment]
HI @mumoshu ,
We are using vals within helmfile and we have some use case when we manage a central secrets file, called `secrets.gotmpl` instead of managing the secrets refs in every helmfile release.

The structure is:
```
environments:
  {{ .Environment.Name }}:
    values:
    - ../providers/{{ .Values.provider }}/secrets.gotmpl
```
This file include some if-else conditions and sometimes part of the secrets are not required, it depends which helmfile releases needs to be deploy.

It will be very helpful to control which secrets would be optional as already discussed [here](https://github.com/roboll/helmfile/issues/1728)

**Comment by mumoshu** [comment]
@Amos-85 Hey! Would you mind filing a feature request to GitHub Discussions of the new helmfile repository?
I think it's feasible to add an additional and optional syntax to environment values entries like the one below to support your use-case, but not sure if everyone agrees, hence I want it to be discussed in Discussions first:

```
environments:
  {{ .Environment.Name }}:
    values:
    - path: ../providers/{{ .Values.provider }}/secrets.gotmpl
      optional: true
```

**Comment by Amos-85** [comment]
I believe by using an optional argument, it will be a global on all secrets included in `secrets.gotmpl`
Maybe this option `ref+gcpsecrets://blablabla?optional` would be better ?

I've created a [discussion](https://github.com/helmfile/helmfile/discussions/391)
Thanks for response.

**Comment by Amos-85** [comment]
Exactly 🙂

**Comment by poligraph** [comment]
@mumoshu 

I am not sure that key toggle is convenient way to use secrets.

for example, 

I previously used construction like this - and if there is no `auth_token` it sets to empty
```
auth_token: "{{ .Values | get "auth_token" "" }}"
```

now I have to use additional function, which fails if there is no secrets in google secret manager and also I cannot set default value.
```
auth_token: "{{ .Values | get "auth_token" | fetchSecretValue }}"
```

additional information:
https://github.com/roboll/helmfile/issues/1728#issuecomment-1217956194

**Comment by mumoshu** [comment]
@poligraph Hey! Perhaps we'd better talk about that in the Helmfile repo but anyway-

You can do something like this today, right?

```
{{ $authTokenKey :=  .Values | get "auth_token" }}
auth_token: "{{ if ne $authTokenKey "" }}{{ fetchSecretValue $authTokenKey }}{{ end }}"
```

**Comment by poligraph** [comment]
@mumoshu I am not sure this code will work, but imagine how many additional code lines we have to add.
It's going to be huge overhead if we use 50+ secrets.

**Comment by mumoshu** [comment]
@poligraph Yeah for sure! It's not easy to extend `fetchSecretValue` just to make your use-case easy because there can be many possible variants each serves a different use-case:

1. `fetchSecretValue $key $defaultValue`
2. `fetchSecretValue $key $fallbackKey1 $fallbackKey2`
3. Just make `fetchSecretValue ""` not to return an error? (But this is going to be a backward-incompatible change so I really don't like doing this.

Which is your preference, to be clear? We'll probably be able to add any of the options above, as a new function. Also, please don't forget to create a dedicate issue in the helmfile repo 😃

**Comment by poligraph** [comment]
@mumoshu I think `fetchSecretValue` should work like `get` function i.e. option 1.

https://github.com/roboll/helmfile/pull/1268/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R535

I will create new issue in helmfile repo.
